package greenthumbgardenplanner;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.JOptionPane;
public class GreenThumbGardenPlanner extends WindowAdapter implements ActionListener {
    JButton btn1,btn2;
    JFrame frame;
    GreenThumbGardenPlanner(){
   frame =new JFrame();
     Label l1=new Label("Welcome to Green Thumb Garden Planner!");
     btn1=new JButton("Plan Layout");
     btn2=new JButton("Select Plants");
      frame.add(l1);
     frame.add(btn1);
      btn1.addActionListener(this);
      btn2.addActionListener(this);
      frame.add(btn2);
      frame.setLocation(280,100);
    frame.setSize(800,600);
    frame.setTitle("Green Thumb Garden Planner");
  frame.setLayout(new FlowLayout());
    frame.setVisible(true);
  frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public static void main(String[] args){
       new GreenThumbGardenPlanner();
    }
    @Override
    public void actionPerformed(ActionEvent e){
        if(e.getSource()==btn1){
        new FirstWindow();
        }
    if(e.getSource()==btn2){
 new  SecondWindow().setVisible(true);
    }    
    }
}
class FirstWindow{
JFrame frame1;
JTextField tf1,tf2;
JLabel l1,l2;
JButton btn;
    FirstWindow(){
          frame1=new JFrame();
          l1=new JLabel("length");
          l2=new JLabel("width");
         tf1=new JTextField();
         tf2=new JTextField();
         btn=new JButton("Draw Layout");
          l1.setBounds(20, 30, 100, 50);
         l2.setBounds(20, 60, 100, 50);
         frame1.add(l1);
         frame1.add(l2);
           frame1.add(tf1);
            tf1.setBounds(80, 48, 30, 20);
          frame1.add(tf2);
            tf2.setBounds(80, 78, 30, 20);
     frame1.add(btn);
     btn.setBounds(120, 65, 120, 20);
           btn.addActionListener(new ActionListener(){
           public void actionPerformed(ActionEvent e){
           int length=Integer.parseInt(tf1.getText());
           int width=Integer.parseInt(tf2.getText());
           }
           });
     frame1.setLayout(null);
    frame1.setTitle("window one");
    frame1.setSize(300, 200);
  frame1.setVisible(true);
 frame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 frame1.setLocation(500,200);
        }
        }
 
 class SecondWindow extends javax.swing.JFrame {

    /**
     * Creates new form WindowFinal
     */
    public SecondWindow() {
        initComponents();
        jButton1.addActionListener(new ActionListener(){
        public void actionPerformed(ActionEvent e){
            JOptionPane.showMessageDialog(new JFrame(), "Plant added to garden !");
     }

        });
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tomato", "Cucumber", "Roses" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("add to garden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButton1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WindowFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WindowFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WindowFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WindowFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WindowFinal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}



